; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan upload dan monitor
upload_speed   = 921600
monitor_speed  = 115200
monitor_filters = esp32_exception_decoder, colorize

; Library dependencies
lib_deps =
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    adafruit/Adafruit BusIO          @ ^1.16.1
    marcoschwartz/LiquidCrystal_I2C  @ ^1.1.4
    knolleary/PubSubClient           @ ^2.8

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM=0

board_build.filesystem = spiffs